### ISSUE TITLE
Double message triggering encoding fallback randomly

### ISSUE THREAD

**Issue by vranki** [matrix-org/matrix-appservice-irc#1052]
This happens very randomly but managed to see it twice in short time.
Encoding fallback is enabled in this network.

 - User sends a message in UTF-8 on IRC
 - Bridge sends it correctly once ä = ä
 - Bridge sends it again, this time with unnecessary latin1 -> UTF-8 conversion  ä = Ã€

What's happening here? Some kind of race condition? Could there be two threads in the encoding function at the same time? Does node-irc claim to be thread safe? Needs to be studied.

**Comment by Half-Shot** [comment]
At a guess, `node-irc` is occasionally encoding a message differently. The IRC Bridge has many client connections at once, so it's normal for potentially 100s of the same message to arrive, but it should be deduped based on the contents of the message. If the message is occasionally being decoded wrongly, then that would explain this bug.

**Comment by vranki** [comment]
Possibly related: https://github.com/matrix-org/synapse/issues/3365

**Comment by Half-Shot** [comment]
Presumably this got fixed with #1081

**Comment by Half-Shot** [comment]
It did not.

**Comment by olmari** [comment]
For any reason we seem to hit this bug more often with ircnet bridge now running 0.24.0, or at least it felt this way to ocme here crying about it :)

![image](https://user-images.githubusercontent.com/5422161/109799348-98411100-7c24-11eb-9327-9cf529dc6a72.png)

Wrongly doubled lines Event Sources, should they be any help:

```
{
  "content": {
    "body": "ei noista saada kaukolämpöä, liian vähän lämpöeroa",
    "msgtype": "m.text"
  },
  "origin_server_ts": 1614768303617,
  "sender": "@_ircnet_<redacted>:irc.snt.utwente.nl",
  "type": "m.room.message",
  "unsigned": {
    "age": 355
  },
  "event_id": "$dZOd65iODgWEw5TSvxNr76NfJJsaf_ancnPguKcj6ZM",
  "room_id": "!OoQtBHsGJuXgqHIska:hacklab.fi"
}
```

```
{
  "content": {
    "body": "ei noista saada kaukolÃ€mpÃ¶Ã€, liian vÃ€hÃ€n lÃ€mpÃ¶eroa",
    "msgtype": "m.text"
  },
  "origin_server_ts": 1614768303794,
  "sender": "@_ircnet_<redacted>:irc.snt.utwente.nl",
  "type": "m.room.message",
  "unsigned": {
    "age": 3113
  },
  "event_id": "$AmfdLTNDQz2iTBVTuQhsp_P7mmM-hmdega4tai9EJj4",
  "room_id": "!OoQtBHsGJuXgqHIska:hacklab.fi"
}
```

```
{
  "content": {
    "body": "ja se pelkkä laskennan sähkönkulutus on ihan posketon noissa kryptovaluutoissa",
    "msgtype": "m.text"
  },
  "origin_server_ts": 1614768351990,
  "sender": "@_ircnet_<redacted>:irc.snt.utwente.nl",
  "type": "m.room.message",
  "unsigned": {
    "age": 1121
  },
  "event_id": "$Di9rrsY7iB-bipz-l47ouBqqqOCTjr6tndKvD6wigMc",
  "room_id": "!OoQtBHsGJuXgqHIska:hacklab.fi"
}
```

```
{
  "content": {
    "body": "ja se pelkkÃ€ laskennan sÃ€hkÃ¶nkulutus on ihan posketon noissa kryptovaluutoissa",
    "msgtype": "m.text"
  },
  "origin_server_ts": 1614768352113,
  "sender": "@_ircnet_<redacted>:irc.snt.utwente.nl",
  "type": "m.room.message",
  "unsigned": {
    "age": 5305
  },
  "event_id": "$8dju4ajGmWFJQCrZv7wX4NLjmjlQIcWhNw5x2rp1qXA",
  "room_id": "!OoQtBHsGJuXgqHIska:hacklab.fi"
}
```

**Comment by vranki** [comment]
Still happening today. It seems less frequent but I can see it perhaps daily.
