### ISSUE TITLE
Let's remove the ' (IRC)' suffix entirely.

### ISSUE THREAD

**Issue by ara4n** [matrix-org/matrix-appservice-irc#194]
It just annoys people, and the mxid is good enough, until we have groups/profiles

**Comment by Kegsay** [comment]
What's the deal on this? We have 248823 `@freenode_` users on the bridge database. I can write a script to rename them all to non-(IRC). I can update the config so subsequent users won't have `(IRC)`. We're currently blocked on Synapse not sucking?

**Comment by ara4n** [comment]
let's just fix the config for now for new users. if we can also update current ones when they next speak, that will probably help too.

**Comment by Kegsay** [comment]
This has been mentioned again, so assigning someone so this doesn't get lost.

I'd rather we didn't have to add code to the bridge to migrate users to the new display name style (like you propose when they "next speak"), as that will inevitably bitrot. I'd much rather do a config change + one time script to enumerate existing users, but I'm concerned that Synapse won't be up to the task of updating that many users. We can't really heavily rate limit this because there's too many of them, 1 per 10s would take 28.8 **days** to adjust. 1 per second would take 2.88 days which may be good enough?

**Comment by Kegsay** [comment]
This has been mitigated because Riot removes " (IRC)" when tab-completing now. We still need to update the names, but the urgency is much less now.

**Comment by Croydon** [comment]
Couldn't that be confusing when when there is one Matrix user and one IRC user with the same nickname/display name and both without profil picture? The only way to distinguish them would be a look on their user information.

On the other hand this (IRC) indeed annoys myself a bit. So not sure what to think about removing it all together.

**Comment by Kegsay** [comment]
@Croydon yes this was why the suffixes were originally added. Really the complete solution is to implement https://github.com/matrix-org/matrix-doc/issues/646

**Comment by jcgruenhage** [comment]
@Croydon Well, if there are two users with the same displayname in one room, riot shows their complete MXID anyway, so that won't be more confusing I think.

**Comment by Half-Shot** [comment]
This has been fixed in the bridge. There is a bug internally for removing the suffixes from existing users.

**Comment by HackerFoo** [comment]
Is there a script to remove the suffix from existing databases? If so, could it be posted or linked here?

**Comment by flackr** [comment]
Is it possible after changing the displayName on my bridge to purge the current users and have them recreated?

**Comment by reuben** [comment]
Was this applied to the bridges run by Matrix? While connected to the Mozilla bridge via Riot I'm still seeing ' (IRC)' suffixes on all users, and autocomplete doesn't let me edit the names afterwards, so I have to type nicknames by hand which gets boring pretty quickly.
